---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	plan_turn(plan_turn)
	whole_lecture(whole_lecture)
	retrieve_evidence(retrieve_evidence)
	check_sufficiency(check_sufficiency)
	synthesize(synthesize)
	transform_prior(transform_prior)
	clarify(clarify)
	record_turn(record_turn)
	__end__([<p>__end__</p>]):::last
	__start__ --> plan_turn;
	check_sufficiency -.-> retrieve_evidence;
	check_sufficiency -.-> synthesize;
	clarify --> record_turn;
	plan_turn -.-> clarify;
	plan_turn -.-> retrieve_evidence;
	plan_turn -.-> transform_prior;
	plan_turn -.-> whole_lecture;
	retrieve_evidence --> check_sufficiency;
	synthesize --> record_turn;
	transform_prior --> record_turn;
	whole_lecture --> record_turn;
	record_turn --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
