-- An uploaded video can carry its own captions.
--
-- A YouTube source gets its transcript free, because the downloader fetches
-- the captions alongside the media. An uploaded file had no such path, so it
-- fell through to paid audio transcription — which for a 102-minute lecture
-- estimates at $0.61 against a $0.50 job cap, meaning uploads of exactly the
-- length this product targets could not finish at all.
--
-- Captions supplied with an upload are the same kind of artifact as captions
-- fetched from YouTube: a timestamped cue file with known provenance. They
-- get their own source kind so the origin stays visible in the transcript's
-- record rather than being disguised as something the pipeline fetched.

alter table video.transcript_sources
    drop constraint transcript_sources_source_kind_check;

alter table video.transcript_sources
    add constraint transcript_sources_source_kind_check check (
        source_kind in (
            'youtube_caption', 'uploaded_caption', 'openrouter_transcription'
        )
    );

comment on column video.transcript_sources.source_kind is
    'Where the timestamped cues came from: fetched captions, captions supplied with an upload, or paid transcription.';

-- A supplied caption file waits here until the stage that consumes it runs.
--
-- It cannot become a transcript on arrival: coverage is measured against the
-- video's duration, and an uploaded video has no duration until ffprobe has
-- seen it. Staging the artifact instead lets captions be uploaded whenever is
-- convenient — before the video bytes, or while they are still transferring —
-- and leaves the transcript stage as the single place that decides which
-- candidate wins.
create table video.caption_uploads (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    video_source_id uuid not null,
    original_filename text,
    storage_backend text not null check (
        storage_backend in ('filesystem', 'supabase', 's3')
    ),
    storage_key text not null check (
        btrim(storage_key) <> '' and storage_key like owner_id::text || '/%'
    ),
    content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
    size_bytes bigint not null check (size_bytes > 0),
    cue_count integer not null check (cue_count > 0),
    created_at timestamptz not null default now(),
    unique (video_source_id, content_hash),
    foreign key (video_id, owner_id)
        references video.videos(id, owner_id) on delete cascade,
    foreign key (video_source_id, video_id, owner_id)
        references video.video_sources(id, video_id, owner_id) on delete cascade
);

create index idx_video_caption_uploads_owner_source
    on video.caption_uploads (owner_id, video_source_id, created_at);

alter table video.caption_uploads enable row level security;

create policy caption_uploads_owner_read on video.caption_uploads
    for select to authenticated using (owner_id = (select auth.uid()));

grant select on video.caption_uploads to authenticated;
