-- Rebuildable, timestamp-addressable visual evidence. Image embeddings are
-- structurally limited to extracted diagram or drawing regions; other visual
-- types participate in retrieval through OCR and model-extracted text.

create table video.frames (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    frame_index integer not null check (frame_index >= 0),
    timestamp_ms bigint not null check (timestamp_ms >= 0),
    selection_reasons text[] not null check (
        coalesce(array_length(selection_reasons, 1), 0) > 0
    ),
    full_storage_backend text not null check (
        full_storage_backend in ('filesystem', 'supabase', 's3')
    ),
    full_storage_key text not null check (
        btrim(full_storage_key) <> ''
        and full_storage_key like owner_id::text || '/%'
    ),
    full_content_hash text not null check (
        full_content_hash ~ '^[0-9a-f]{64}$'
    ),
    preview_storage_backend text not null check (
        preview_storage_backend in ('filesystem', 'supabase', 's3')
    ),
    preview_storage_key text not null check (
        btrim(preview_storage_key) <> ''
        and preview_storage_key like owner_id::text || '/%'
    ),
    preview_content_hash text not null check (
        preview_content_hash ~ '^[0-9a-f]{64}$'
    ),
    perceptual_hash text not null check (
        perceptual_hash ~ '^[0-9a-f]{16,64}$'
    ),
    width integer not null check (width > 0),
    height integer not null check (height > 0),
    ocr_text text not null default '',
    ocr_confidence double precision check (
        ocr_confidence is null or ocr_confidence between 0 and 1
    ),
    ocr_engine text,
    ocr_version text,
    created_at timestamptz not null default now(),
    unique (id, ingestion_version_id, video_id, owner_id),
    unique (ingestion_version_id, frame_index),
    unique (ingestion_version_id, timestamp_ms),
    foreign key (ingestion_version_id, video_id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        on delete cascade
);

create index idx_video_frames_owner_video_timestamp
    on video.frames (owner_id, video_id, ingestion_version_id, timestamp_ms);
create index idx_video_frames_owner_full_hash
    on video.frames (owner_id, full_content_hash);

create table video.visual_observations (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    frame_id bigint not null,
    status text not null check (status in ('success', 'failed')),
    visual_types text[] not null default '{}'::text[] check (
        visual_types <@ array[
            'slide', 'code', 'equation', 'diagram', 'drawing', 'chart',
            'ui', 'terminal', 'person', 'other'
        ]::text[]
    ),
    summary text,
    visible_text text not null default '',
    technical_details_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(technical_details_json) = 'object'
    ),
    importance double precision check (
        importance is null or importance between 0 and 1
    ),
    confidence double precision check (
        confidence is null or confidence between 0 and 1
    ),
    model_name text not null check (btrim(model_name) <> ''),
    model_revision text not null check (btrim(model_revision) <> ''),
    prompt_version text not null check (btrim(prompt_version) <> ''),
    input_hash text not null check (input_hash ~ '^[0-9a-f]{64}$'),
    cost_usd numeric(10, 6) not null default 0 check (cost_usd >= 0),
    error_code text,
    error_message text,
    created_at timestamptz not null default now(),
    unique (id, frame_id, ingestion_version_id, video_id, owner_id),
    unique (frame_id),
    foreign key (frame_id, ingestion_version_id, video_id, owner_id)
        references video.frames(id, ingestion_version_id, video_id, owner_id)
        on delete cascade,
    check (
        (status = 'success'
            and summary is not null
            and btrim(summary) <> ''
            and coalesce(array_length(visual_types, 1), 0) > 0
            and error_code is null
            and error_message is null)
        or
        (status = 'failed'
            and summary is null
            and coalesce(array_length(visual_types, 1), 0) = 0
            and error_code is not null
            and btrim(error_code) <> '')
    )
);

create index idx_video_visual_observations_owner_version
    on video.visual_observations (
        owner_id, video_id, ingestion_version_id, status
    );

create table video.visual_regions (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    frame_id bigint not null,
    visual_observation_id bigint not null,
    region_index integer not null check (region_index >= 0),
    region_type text not null check (region_type in ('diagram', 'drawing')),
    x double precision not null check (x between 0 and 1),
    y double precision not null check (y between 0 and 1),
    width double precision not null check (width > 0 and width <= 1),
    height double precision not null check (height > 0 and height <= 1),
    summary text not null check (btrim(summary) <> ''),
    crop_storage_backend text not null check (
        crop_storage_backend in ('filesystem', 'supabase', 's3')
    ),
    crop_storage_key text not null check (
        btrim(crop_storage_key) <> ''
        and crop_storage_key like owner_id::text || '/%'
    ),
    crop_content_hash text not null check (
        crop_content_hash ~ '^[0-9a-f]{64}$'
    ),
    model_name text not null check (btrim(model_name) <> ''),
    model_revision text not null check (btrim(model_revision) <> ''),
    prompt_version text not null check (btrim(prompt_version) <> ''),
    input_hash text not null check (input_hash ~ '^[0-9a-f]{64}$'),
    confidence double precision check (
        confidence is null or confidence between 0 and 1
    ),
    cost_usd numeric(10, 6) not null default 0 check (cost_usd >= 0),
    created_at timestamptz not null default now(),
    unique (id, ingestion_version_id, video_id, owner_id),
    unique (id, frame_id, ingestion_version_id, video_id, owner_id),
    unique (visual_observation_id, region_index),
    foreign key (
        visual_observation_id, frame_id, ingestion_version_id,
        video_id, owner_id
    ) references video.visual_observations(
        id, frame_id, ingestion_version_id, video_id, owner_id
    ) on delete cascade,
    check (x + width <= 1),
    check (y + height <= 1)
);

create index idx_video_visual_regions_owner_version
    on video.visual_regions (
        owner_id, video_id, ingestion_version_id, frame_id
    );

create table video.visual_events (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    start_frame_id bigint not null,
    end_frame_id bigint not null,
    event_type text not null check (
        event_type in ('transition', 'demonstration', 'annotation', 'other')
    ),
    start_ms bigint not null check (start_ms >= 0),
    end_ms bigint not null check (end_ms > start_ms),
    summary text not null check (btrim(summary) <> ''),
    details_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(details_json) = 'object'
    ),
    model_name text not null check (btrim(model_name) <> ''),
    model_revision text not null check (btrim(model_revision) <> ''),
    prompt_version text not null check (btrim(prompt_version) <> ''),
    input_hash text not null check (input_hash ~ '^[0-9a-f]{64}$'),
    cost_usd numeric(10, 6) not null default 0 check (cost_usd >= 0),
    created_at timestamptz not null default now(),
    unique (id, ingestion_version_id, video_id, owner_id),
    foreign key (start_frame_id, ingestion_version_id, video_id, owner_id)
        references video.frames(id, ingestion_version_id, video_id, owner_id)
        on delete cascade,
    foreign key (end_frame_id, ingestion_version_id, video_id, owner_id)
        references video.frames(id, ingestion_version_id, video_id, owner_id)
        on delete cascade
);

create index idx_video_visual_events_owner_version_start
    on video.visual_events (
        owner_id, video_id, ingestion_version_id, start_ms
    );

alter table video.resource_pages
    add constraint resource_pages_id_owner_key unique (id, owner_id);

create table video.evidence_units (
    id text not null check (id ~ '^[0-9a-f]{64}$'),
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    modality text not null check (modality in (
        'transcript', 'visual_frame', 'visual_event', 'resource_page'
    )),
    transcript_segment_id bigint,
    frame_id bigint,
    visual_event_id bigint,
    resource_page_id bigint,
    retrieval_text text not null check (btrim(retrieval_text) <> ''),
    start_ms bigint check (start_ms is null or start_ms >= 0),
    end_ms bigint check (
        end_ms is null or (start_ms is not null and end_ms >= start_ms)
    ),
    page_number integer check (page_number is null or page_number > 0),
    content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
    search_vector tsvector generated always as (
        to_tsvector('simple', coalesce(retrieval_text, ''))
    ) stored,
    created_at timestamptz not null default now(),
    primary key (id, owner_id),
    unique (id, ingestion_version_id, video_id, owner_id),
    unique (id, frame_id, ingestion_version_id, video_id, owner_id),
    foreign key (ingestion_version_id, video_id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        on delete cascade,
    foreign key (transcript_segment_id, video_id, owner_id)
        references video.transcript_segments(id, video_id, owner_id)
        on delete cascade,
    foreign key (frame_id, ingestion_version_id, video_id, owner_id)
        references video.frames(id, ingestion_version_id, video_id, owner_id)
        on delete cascade,
    foreign key (visual_event_id, ingestion_version_id, video_id, owner_id)
        references video.visual_events(id, ingestion_version_id, video_id, owner_id)
        on delete cascade,
    foreign key (resource_page_id, owner_id)
        references video.resource_pages(id, owner_id) on delete cascade,
    check (
        num_nonnulls(
            transcript_segment_id, frame_id, visual_event_id, resource_page_id
        ) = 1
    ),
    check (
        (modality = 'transcript'
            and transcript_segment_id is not null
            and start_ms is not null
            and end_ms is not null
            and page_number is null)
        or
        (modality = 'visual_frame'
            and frame_id is not null
            and start_ms is not null
            and end_ms is not null
            and page_number is null)
        or
        (modality = 'visual_event'
            and visual_event_id is not null
            and start_ms is not null
            and end_ms is not null
            and page_number is null)
        or
        (modality = 'resource_page'
            and resource_page_id is not null
            and start_ms is null
            and end_ms is null
            and page_number is not null)
    )
);

create index idx_video_evidence_units_owner_version_modality
    on video.evidence_units (
        owner_id, video_id, ingestion_version_id, modality
    );
create index idx_video_evidence_units_search
    on video.evidence_units using gin (search_vector);

create or replace function video.validate_evidence_locator()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
    source_start_ms bigint;
    source_end_ms bigint;
    source_page_number integer;
    source_resource_id uuid;
begin
    if new.modality = 'transcript' then
        select segment.start_ms, segment.end_ms
        into source_start_ms, source_end_ms
        from video.transcript_segments as segment
        where segment.id = new.transcript_segment_id
          and segment.video_id = new.video_id
          and segment.owner_id = new.owner_id;
    elsif new.modality = 'visual_frame' then
        select frame.timestamp_ms, frame.timestamp_ms
        into source_start_ms, source_end_ms
        from video.frames as frame
        where frame.id = new.frame_id
          and frame.ingestion_version_id = new.ingestion_version_id
          and frame.video_id = new.video_id
          and frame.owner_id = new.owner_id;
    elsif new.modality = 'visual_event' then
        select event.start_ms, event.end_ms
        into source_start_ms, source_end_ms
        from video.visual_events as event
        where event.id = new.visual_event_id
          and event.ingestion_version_id = new.ingestion_version_id
          and event.video_id = new.video_id
          and event.owner_id = new.owner_id;
    elsif new.modality = 'resource_page' then
        select page.page_number, page.resource_id
        into source_page_number, source_resource_id
        from video.resource_pages as page
        where page.id = new.resource_page_id
          and page.owner_id = new.owner_id;

        if source_page_number is null
           or source_page_number is distinct from new.page_number
           or not exists (
                select 1
                from video.video_resources as linked
                where linked.video_id = new.video_id
                  and linked.resource_id = source_resource_id
                  and linked.owner_id = new.owner_id
           ) then
            raise check_violation using message =
                'resource evidence must match a page linked to this video';
        end if;
        return new;
    end if;

    if source_start_ms is null
       or source_start_ms is distinct from new.start_ms
       or source_end_ms is distinct from new.end_ms then
        raise check_violation using message =
            'evidence timestamps must match the typed source locator';
    end if;
    return new;
end;
$$;

create trigger evidence_units_validate_locator
    before insert or update on video.evidence_units
    for each row execute function video.validate_evidence_locator();

create table video.evidence_embeddings (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    evidence_id text not null,
    embedding_kind text not null check (embedding_kind in ('text', 'image')),
    visual_region_id bigint,
    evidence_frame_id bigint,
    model_name text not null check (btrim(model_name) <> ''),
    model_revision text not null check (btrim(model_revision) <> ''),
    dimension integer not null check (dimension > 0),
    document_format_version text not null check (
        btrim(document_format_version) <> ''
    ),
    embedding_input_hash text not null check (
        embedding_input_hash ~ '^[0-9a-f]{64}$'
    ),
    embedding extensions.vector not null,
    created_at timestamptz not null default now(),
    foreign key (evidence_id, ingestion_version_id, video_id, owner_id)
        references video.evidence_units(
            id, ingestion_version_id, video_id, owner_id
        ) on delete cascade,
    foreign key (
        evidence_id, evidence_frame_id, ingestion_version_id,
        video_id, owner_id
    ) references video.evidence_units(
        id, frame_id, ingestion_version_id, video_id, owner_id
    ) on delete cascade,
    foreign key (
        visual_region_id, evidence_frame_id, ingestion_version_id,
        video_id, owner_id
    )
        references video.visual_regions(
            id, frame_id, ingestion_version_id, video_id, owner_id
        ) on delete cascade,
    check (extensions.vector_dims(embedding) = dimension),
    check (
        (embedding_kind = 'text'
            and visual_region_id is null
            and evidence_frame_id is null)
        or
        (embedding_kind = 'image'
            and visual_region_id is not null
            and evidence_frame_id is not null)
    )
);

create unique index idx_video_evidence_embeddings_text_unique
    on video.evidence_embeddings (
        owner_id, evidence_id, model_name, model_revision,
        document_format_version
    ) where embedding_kind = 'text';
create unique index idx_video_evidence_embeddings_image_unique
    on video.evidence_embeddings (
        owner_id, evidence_id, visual_region_id, model_name, model_revision,
        document_format_version
    ) where embedding_kind = 'image';
create index idx_video_evidence_embeddings_owner_version
    on video.evidence_embeddings (
        owner_id, video_id, ingestion_version_id, embedding_kind
    );

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'frames', 'visual_observations', 'visual_regions', 'visual_events',
        'evidence_units', 'evidence_embeddings'
    ] loop
        execute format('alter table video.%I enable row level security', table_name);
        execute format(
            'create policy %I on video.%I for select to authenticated '
            'using (owner_id = (select auth.uid()))',
            table_name || '_owner_read',
            table_name
        );
        execute format(
            'grant select on video.%I to authenticated',
            table_name
        );
    end loop;
end $$;

comment on table video.visual_regions is
    'Model-extracted diagram or drawing crops; the only visual objects eligible for image embeddings.';
comment on table video.evidence_units is
    'Versioned retrieval text with exactly one typed, owner-safe source locator.';
