-- Durable transcript inputs and the resumable, versioned video-ingestion
-- workflow. Rows in this migration preserve enough provenance to rebuild all
-- visual and retrieval artifacts introduced by later migrations.

create table video.transcript_sources (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    video_id uuid not null,
    video_source_id uuid not null,
    source_kind text not null check (
        source_kind in ('youtube_caption', 'openrouter_transcription')
    ),
    language text not null check (btrim(language) <> ''),
    provider text not null check (btrim(provider) <> ''),
    model_name text,
    model_revision text,
    storage_backend text not null check (
        storage_backend in ('filesystem', 'supabase', 's3')
    ),
    storage_key text not null check (
        btrim(storage_key) <> ''
        and storage_key like owner_id::text || '/%'
    ),
    content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
    timing_kind text not null check (timing_kind in ('cue', 'word')),
    coverage_ratio double precision check (
        coverage_ratio is null or coverage_ratio between 0 and 1
    ),
    detected_speech boolean,
    provenance_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(provenance_json) = 'object'
    ),
    cost_usd numeric(10, 6) not null default 0 check (cost_usd >= 0),
    created_at timestamptz not null default now(),
    unique (id, video_id, owner_id),
    unique (video_source_id, content_hash),
    foreign key (video_id, owner_id)
        references video.videos(id, owner_id) on delete cascade,
    foreign key (video_source_id, video_id, owner_id)
        references video.video_sources(id, video_id, owner_id) on delete cascade,
    check (
        source_kind <> 'openrouter_transcription'
        or (model_name is not null and btrim(model_name) <> '')
    )
);

create table video.transcript_segments (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    video_id uuid not null,
    transcript_source_id uuid not null,
    cue_index integer not null check (cue_index >= 0),
    start_ms bigint not null check (start_ms >= 0),
    end_ms bigint not null check (end_ms > start_ms),
    text text not null check (btrim(text) <> ''),
    speaker text,
    confidence double precision check (
        confidence is null or confidence between 0 and 1
    ),
    raw_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(raw_json) = 'object'
    ),
    unique (id, video_id, owner_id),
    unique (transcript_source_id, cue_index),
    foreign key (transcript_source_id, video_id, owner_id)
        references video.transcript_sources(id, video_id, owner_id)
        on delete cascade
);

create index idx_video_transcript_sources_owner_video
    on video.transcript_sources (owner_id, video_id, created_at desc);
create index idx_video_transcript_segments_owner_video_start
    on video.transcript_segments (owner_id, video_id, start_ms);

alter table video.resources
    add constraint resources_id_owner_kind_key
    unique (id, owner_id, resource_kind);

create table video.resource_pages (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    resource_id uuid not null,
    resource_kind text not null default 'pdf' check (resource_kind = 'pdf'),
    page_number integer not null check (page_number > 0),
    text_content text not null default '',
    layout_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(layout_json) = 'object'
    ),
    content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
    parser_version text not null check (btrim(parser_version) <> ''),
    parser_config_hash text not null check (
        parser_config_hash ~ '^[0-9a-f]{64}$'
    ),
    render_storage_backend text check (
        render_storage_backend is null
        or render_storage_backend in ('filesystem', 'supabase', 's3')
    ),
    render_storage_key text,
    render_content_hash text check (
        render_content_hash is null
        or render_content_hash ~ '^[0-9a-f]{64}$'
    ),
    created_at timestamptz not null default now(),
    unique (id, resource_id, owner_id),
    unique (resource_id, page_number),
    foreign key (resource_id, owner_id, resource_kind)
        references video.resources(id, owner_id, resource_kind)
        on delete cascade,
    check (
        (render_storage_backend is null
            and render_storage_key is null
            and render_content_hash is null)
        or
        (render_storage_backend is not null
            and render_storage_key is not null
            and btrim(render_storage_key) <> ''
            and render_storage_key like owner_id::text || '/%'
            and render_content_hash is not null)
    )
);

create index idx_video_resource_pages_owner_resource
    on video.resource_pages (owner_id, resource_id, page_number);

create table video.ingestion_versions (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    video_id uuid not null,
    video_source_id uuid not null,
    version_number integer not null check (version_number > 0),
    status text not null default 'building' check (
        status in ('building', 'ready', 'degraded', 'failed', 'cancelled')
    ),
    config_json jsonb not null check (jsonb_typeof(config_json) = 'object'),
    config_hash text not null check (config_hash ~ '^[0-9a-f]{64}$'),
    dependency_hashes_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(dependency_hashes_json) = 'object'
    ),
    model_prompt_versions_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(model_prompt_versions_json) = 'object'
    ),
    resource_set_hash text check (
        resource_set_hash is null or resource_set_hash ~ '^[0-9a-f]{64}$'
    ),
    quality_gates_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(quality_gates_json) = 'object'
    ),
    cost_cap_usd numeric(10, 6) not null default 0.50 check (
        cost_cap_usd > 0
    ),
    actual_cost_usd numeric(10, 6) not null default 0 check (
        actual_cost_usd >= 0 and actual_cost_usd <= cost_cap_usd
    ),
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    published_at timestamptz,
    error_code text,
    error_message text,
    unique (id, video_id, owner_id),
    unique (video_id, version_number),
    foreign key (video_id, owner_id)
        references video.videos(id, owner_id) on delete cascade,
    foreign key (video_source_id, video_id, owner_id)
        references video.video_sources(id, video_id, owner_id) on delete cascade,
    check (
        (status in ('ready', 'degraded', 'failed', 'cancelled'))
        = (completed_at is not null)
    ),
    check (
        (status in ('ready', 'degraded')) = (published_at is not null)
    ),
    check (
        status not in ('ready', 'degraded')
        or quality_gates_json <> '{}'::jsonb
    ),
    check (published_at is null or published_at >= started_at),
    check (completed_at is null or completed_at >= started_at),
    check (published_at is null or published_at <= completed_at)
);

alter table video.videos
    add column current_ingestion_version_id uuid,
    add constraint videos_current_ingestion_version_fkey
        foreign key (current_ingestion_version_id, id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        deferrable initially deferred,
    add constraint videos_ready_requires_current_version
        check (
            (readiness_status in ('ready', 'degraded'))
            = (current_ingestion_version_id is not null)
        );

create or replace function video.validate_current_ingestion_version()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
    version_status text;
begin
    if new.current_ingestion_version_id is null then
        return new;
    end if;

    select current.status
    into version_status
    from video.ingestion_versions as current
    where current.id = new.current_ingestion_version_id
      and current.video_id = new.id
      and current.owner_id = new.owner_id;

    if version_status is null or version_status <> new.readiness_status then
        raise check_violation using message =
            'current ingestion version must be published with the same readiness status';
    end if;
    return new;
end;
$$;

create trigger videos_validate_current_ingestion_version
    before insert or update of current_ingestion_version_id, readiness_status
    on video.videos
    for each row execute function video.validate_current_ingestion_version();

create index idx_video_ingestion_versions_owner_video
    on video.ingestion_versions (owner_id, video_id, version_number desc);

create table video.ingestion_jobs (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    video_id uuid not null,
    target_version_id uuid not null,
    idempotency_key uuid not null,
    status text not null check (status in (
        'awaiting_upload', 'queued', 'running', 'retry_scheduled',
        'ready', 'failed', 'cancelled'
    )),
    stage text check (stage is null or stage in (
        'acquire_source', 'media_metadata', 'transcript', 'resources',
        'frame_selection', 'ocr', 'visual_analysis', 'spatial_regions',
        'indexing', 'quality_gates', 'publish'
    )),
    progress_completed integer not null default 0 check (
        progress_completed >= 0
    ),
    progress_total integer check (
        progress_total is null or progress_total >= 0
    ),
    progress_unit text,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    max_attempts integer not null default 3 check (max_attempts > 0),
    next_attempt_at timestamptz,
    lease_owner text,
    lease_expires_at timestamptz,
    heartbeat_at timestamptz,
    cancellation_requested_at timestamptz,
    last_error_code text,
    last_error_message text,
    last_error_retryable boolean,
    staging_storage_backend text check (
        staging_storage_backend is null
        or staging_storage_backend in ('filesystem', 'supabase', 's3')
    ),
    staging_storage_key text,
    cost_cap_usd numeric(10, 6) not null default 0.50 check (
        cost_cap_usd > 0
    ),
    actual_cost_usd numeric(10, 6) not null default 0 check (
        actual_cost_usd >= 0 and actual_cost_usd <= cost_cap_usd
    ),
    provenance_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(provenance_json) = 'object'
    ),
    created_at timestamptz not null default now(),
    started_at timestamptz,
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (id, owner_id),
    unique (id, video_id, owner_id),
    unique (owner_id, idempotency_key),
    foreign key (video_id, owner_id)
        references video.videos(id, owner_id) on delete cascade,
    foreign key (target_version_id, video_id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        on delete cascade,
    check (
        (staging_storage_backend is null and staging_storage_key is null)
        or
        (staging_storage_backend is not null
            and staging_storage_key is not null
            and btrim(staging_storage_key) <> ''
            and staging_storage_key like owner_id::text || '/%')
    ),
    check (
        (status in ('ready', 'failed', 'cancelled'))
        = (completed_at is not null)
    ),
    check (
        progress_total is null or progress_completed <= progress_total
    ),
    check (started_at is null or started_at >= created_at),
    check (completed_at is null or completed_at >= created_at)
);

create unique index idx_video_ingestion_jobs_one_active
    on video.ingestion_jobs (owner_id, video_id)
    where status in (
        'awaiting_upload', 'queued', 'running', 'retry_scheduled'
    );
create index idx_video_ingestion_jobs_claimable
    on video.ingestion_jobs (next_attempt_at nulls first, created_at, id)
    where status in ('queued', 'retry_scheduled');
create index idx_video_ingestion_jobs_owner_created
    on video.ingestion_jobs (owner_id, created_at desc);
create index idx_video_ingestion_jobs_lease
    on video.ingestion_jobs (lease_expires_at)
    where lease_expires_at is not null;

create table video.ingestion_job_events (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    job_id uuid not null,
    event_type text not null check (btrim(event_type) <> ''),
    status text,
    stage text,
    message text,
    metadata_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(metadata_json) = 'object'
    ),
    created_at timestamptz not null default now(),
    foreign key (job_id, owner_id)
        references video.ingestion_jobs(id, owner_id) on delete cascade
);

create index idx_video_ingestion_job_events_owner_job
    on video.ingestion_job_events (owner_id, job_id, id);

create table video.ingestion_stage_checkpoints (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    stage text not null check (stage in (
        'acquire_source', 'media_metadata', 'transcript', 'resources',
        'frame_selection', 'ocr', 'visual_analysis', 'spatial_regions',
        'indexing', 'quality_gates', 'publish'
    )),
    status text not null default 'pending' check (
        status in ('pending', 'running', 'complete', 'failed', 'invalidated')
    ),
    dependency_hash text not null check (
        dependency_hash ~ '^[0-9a-f]{64}$'
    ),
    output_manifest_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(output_manifest_json) = 'object'
    ),
    provenance_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(provenance_json) = 'object'
    ),
    actual_cost_usd numeric(10, 6) not null default 0 check (
        actual_cost_usd >= 0
    ),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    reused_from_checkpoint_id uuid,
    started_at timestamptz,
    completed_at timestamptz,
    error_code text,
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, video_id, owner_id),
    unique (id, video_id, owner_id, stage, dependency_hash),
    unique (ingestion_version_id, stage),
    foreign key (ingestion_version_id, video_id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        on delete cascade,
    foreign key (
        reused_from_checkpoint_id, video_id, owner_id, stage, dependency_hash
    ) references video.ingestion_stage_checkpoints(
        id, video_id, owner_id, stage, dependency_hash
    )
        on delete set null (reused_from_checkpoint_id),
    check (
        (status in ('complete', 'failed', 'invalidated'))
        = (completed_at is not null)
    ),
    check (reused_from_checkpoint_id is null or status = 'complete'),
    check (completed_at is null or started_at is null or completed_at >= started_at)
);

create index idx_video_stage_checkpoints_owner_version
    on video.ingestion_stage_checkpoints (
        owner_id, ingestion_version_id, stage
    );

create table video.resource_suggestions (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    video_id uuid not null,
    job_id uuid,
    suggested_kind text not null check (
        suggested_kind in ('pdf', 'external_link')
    ),
    url text not null check (btrim(url) <> ''),
    normalized_url text not null check (btrim(normalized_url) <> ''),
    title text,
    reason text,
    status text not null default 'pending' check (
        status in ('pending', 'confirmed', 'dismissed')
    ),
    confirmed_resource_id uuid,
    created_at timestamptz not null default now(),
    resolved_at timestamptz,
    unique (id, video_id, owner_id),
    unique (video_id, normalized_url),
    foreign key (video_id, owner_id)
        references video.videos(id, owner_id) on delete cascade,
    foreign key (job_id, video_id, owner_id)
        references video.ingestion_jobs(id, video_id, owner_id)
        on delete cascade,
    foreign key (confirmed_resource_id, owner_id)
        references video.resources(id, owner_id),
    check (
        (status = 'pending'
            and confirmed_resource_id is null
            and resolved_at is null)
        or
        (status = 'confirmed'
            and confirmed_resource_id is not null
            and resolved_at is not null)
        or
        (status = 'dismissed'
            and confirmed_resource_id is null
            and resolved_at is not null)
    )
);

create index idx_video_resource_suggestions_owner_video
    on video.resource_suggestions (owner_id, video_id, status, created_at);

create trigger video_ingestion_jobs_set_updated_at
    before update on video.ingestion_jobs
    for each row execute function video.set_updated_at();
create trigger video_stage_checkpoints_set_updated_at
    before update on video.ingestion_stage_checkpoints
    for each row execute function video.set_updated_at();

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'transcript_sources', 'transcript_segments', 'resource_pages',
        'ingestion_versions', 'ingestion_jobs', 'ingestion_job_events',
        'ingestion_stage_checkpoints', 'resource_suggestions'
    ] loop
        execute format('alter table video.%I enable row level security', table_name);
        execute format(
            'create policy %I on video.%I for select to authenticated '
            'using (owner_id = (select auth.uid()))',
            table_name || '_owner_read',
            table_name
        );
        execute format(
            'grant select on video.%I to authenticated',
            table_name
        );
    end loop;
end $$;

comment on table video.ingestion_stage_checkpoints is
    'Dependency-keyed stage outputs used for selective invalidation, restart, and paid-result reuse.';
comment on column video.ingestion_versions.quality_gates_json is
    'Modality-aware gate results; only a published ready or degraded version may become current.';
