-- Multi-user PDF ingestion: durable jobs, append-only events, book readiness,
-- and the private source bucket promoted from supabase/deferred/.

-- Books gain explicit lifecycle information. Existing rows were imported by
-- the manual pipeline and are complete, so they are backfilled as ready.
alter table public.books
    add column status text not null default 'processing'
        check (status in ('processing', 'ready', 'failed')),
    add column ready_at timestamptz,
    add column ingestion_job_id uuid,
    add constraint books_ready_requires_timestamp
        check ((status = 'ready') = (ready_at is not null));

update public.books set status = 'ready', ready_at = parsed_at;

create table public.ingestion_jobs (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null references auth.users(id) on delete cascade,
    idempotency_key uuid not null,
    status text not null check (status in (
        'awaiting_upload', 'queued', 'validating', 'parsing', 'persisting',
        'chunking', 'embedding', 'verifying', 'ready',
        'retry_scheduled', 'failed', 'cancelled',
        -- Reserved for the scanned/TOC-less follow-up workflow.
        'classifying', 'ocr', 'needs_toc_review'
    )),
    stage text check (stage is null or stage in (
        'verify_upload', 'download_source', 'preflight', 'parse_pages',
        'persist_canonical', 'build_chunks', 'build_embeddings', 'verify_book',
        'classify', 'ocr_pages', 'propose_toc'
    )),
    document_class text check (document_class is null or document_class in (
        'structured_digital', 'digital_without_toc', 'scanned', 'mixed',
        'unsupported'
    )),
    storage_bucket text not null,
    storage_path text not null,
    original_filename text not null check (btrim(original_filename) <> ''),
    declared_content_type text,
    declared_size_bytes bigint check (
        declared_size_bytes is null or declared_size_bytes >= 0
    ),
    verified_size_bytes bigint check (
        verified_size_bytes is null or verified_size_bytes >= 0
    ),
    file_hash text check (file_hash is null or file_hash ~ '^[0-9a-f]{64}$'),
    page_count integer check (page_count is null or page_count > 0),
    book_id bigint,
    progress_completed integer not null default 0
        check (progress_completed >= 0),
    progress_total integer check (progress_total is null or progress_total >= 0),
    progress_unit text,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    max_attempts integer not null default 3 check (max_attempts > 0),
    next_attempt_at timestamptz,
    lease_owner text,
    lease_expires_at timestamptz,
    heartbeat_at timestamptz,
    cancellation_requested_at timestamptz,
    last_error_code text,
    last_error_message text,
    last_error_retryable boolean,
    -- Parser, OCR, chunker, and embedding provenance recorded per stage.
    provenance_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (id, owner_id),
    unique (owner_id, idempotency_key),
    unique (owner_id, storage_path),
    -- A ready job must name the book it produced.
    check (status <> 'ready' or book_id is not null),
    -- Deleting a book deletes the job that produced it and its events. The
    -- alternative, nulling book_id, would contradict the check above and leave
    -- a "ready" job pointing at nothing.
    foreign key (book_id, owner_id)
        references public.books(id, owner_id) on delete cascade
);

alter table public.books
    add constraint books_ingestion_job_fkey
    foreign key (ingestion_job_id, owner_id)
        references public.ingestion_jobs(id, owner_id)
        on delete set null (ingestion_job_id);

create table public.ingestion_job_events (
    id bigint generated by default as identity primary key,
    job_id uuid not null,
    owner_id uuid not null,
    event_type text not null check (btrim(event_type) <> ''),
    status text,
    stage text,
    message text,
    metadata_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    foreign key (job_id, owner_id)
        references public.ingestion_jobs(id, owner_id) on delete cascade
);

-- One job per owner may hold the worker at a time. Queued depth is a
-- separate application quota because a partial unique index cannot count.
create unique index idx_ingestion_jobs_single_active
    on public.ingestion_jobs (owner_id)
    where status in (
        'validating', 'parsing', 'persisting', 'chunking', 'embedding',
        'verifying', 'classifying', 'ocr'
    );

-- Deterministic claim order for the worker's FOR UPDATE SKIP LOCKED poll.
create index idx_ingestion_jobs_claimable
    on public.ingestion_jobs (next_attempt_at nulls first, created_at, id)
    where status in ('queued', 'retry_scheduled');

create index idx_ingestion_jobs_owner_created
    on public.ingestion_jobs (owner_id, created_at desc);
create index idx_ingestion_jobs_lease
    on public.ingestion_jobs (lease_expires_at)
    where lease_expires_at is not null;
create index idx_ingestion_job_events_job
    on public.ingestion_job_events (owner_id, job_id, id);
create index idx_books_owner_status
    on public.books (owner_id, status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    -- clock_timestamp(), not now(): several job updates can share one
    -- transaction and each should record when it actually happened.
    new.updated_at = clock_timestamp();
    return new;
end;
$$;

create trigger ingestion_jobs_set_updated_at
    before update on public.ingestion_jobs
    for each row execute function public.set_updated_at();

-- Browser-facing reads go through PostgREST and must stay owner-scoped. All
-- writes happen server-side through the API and worker, which additionally
-- filter by owner in every statement.
alter table public.ingestion_jobs enable row level security;
alter table public.ingestion_job_events enable row level security;

create policy ingestion_jobs_owner_read on public.ingestion_jobs
    for select to authenticated
    using (owner_id = (select auth.uid()));

create policy ingestion_job_events_owner_read on public.ingestion_job_events
    for select to authenticated
    using (owner_id = (select auth.uid()));

grant select on public.ingestion_jobs to authenticated;
grant select on public.ingestion_job_events to authenticated;

-- Private source bucket, promoted from supabase/deferred/book_sources_storage.sql.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'book-sources',
    'book-sources',
    false,
    52428800,
    array['application/pdf']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "book_sources_owner_select"
on storage.objects for select to authenticated
using (
    bucket_id = 'book-sources'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "book_sources_owner_insert"
on storage.objects for insert to authenticated
with check (
    bucket_id = 'book-sources'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);

-- No update policy: source objects are immutable at {owner_id}/{job_id}/original.pdf
-- and upsert is disabled, so a second upload cannot overwrite a verified source.

create policy "book_sources_owner_delete"
on storage.objects for delete to authenticated
using (
    bucket_id = 'book-sources'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
);
