-- Persisted study conversations.
--
-- Conversation state previously existed only in the browser: the client held
-- the whole `ConversationState` and posted it back on every turn, so the only
-- copy of a conversation lived in one tab and any client could submit
-- arbitrary state. These tables move that ownership to the server.
--
-- `conversation_turns` is canonical. `conversations.state_json` is a derived
-- resume checkpoint that could be rebuilt by replaying turns; it is stored
-- rather than recomputed because rebuilding it on every turn is wasted work,
-- not because it is authoritative. This is the same source/derived split the
-- rest of the schema follows.

create table public.conversations (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null references auth.users(id) on delete cascade,
    title text not null check (btrim(title) <> ''),
    -- The books this conversation may search. Non-empty by construction: an
    -- empty selection must never be readable as "the whole library".
    book_ids bigint[] not null check (cardinality(book_ids) > 0),
    retrieval_mode text not null default 'hybrid'
        check (retrieval_mode in ('bm25', 'vector', 'hybrid', 'hybrid_rerank')),
    state_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, owner_id)
);

create table public.conversation_turns (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    conversation_id uuid not null,
    turn_index integer not null check (turn_index >= 0),
    question text not null check (btrim(question) <> ''),
    answer text not null,
    -- The full TurnResult. Rendering references, citations, and the answer
    -- inspector on resume needs the same structure a live turn produced, so
    -- storing the answer text alone would degrade a resumed conversation.
    result_json jsonb not null,
    created_at timestamptz not null default now(),
    unique (conversation_id, turn_index),
    foreign key (conversation_id, owner_id)
        references public.conversations(id, owner_id) on delete cascade
);

create index idx_conversations_owner_updated
    on public.conversations (owner_id, updated_at desc);
create index idx_conversation_turns_conversation
    on public.conversation_turns (conversation_id, turn_index);

do $$
declare
    table_name text;
begin
    foreach table_name in array array['conversations', 'conversation_turns']
    loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format(
            'create policy %I on public.%I for all to authenticated '
            'using (owner_id = (select auth.uid())) '
            'with check (owner_id = (select auth.uid()))',
            table_name || '_owner_access',
            table_name
        );
        execute format(
            'grant select, insert, update, delete on public.%I to authenticated',
            table_name
        );
    end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;
