-- Version aligned with the hosted migration recorded by Supabase MCP.
create schema if not exists extensions;
create extension if not exists vector with schema extensions;

create table public.books (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    title text not null check (btrim(title) <> ''),
    author text,
    source_path text not null,
    source_filename text not null,
    source_storage_bucket text,
    source_storage_path text,
    file_hash text not null check (file_hash ~ '^[0-9a-f]{64}$'),
    page_count integer check (page_count is null or page_count > 0),
    parser_version text not null,
    parsed_at timestamptz not null,
    metadata_json jsonb not null default '{}'::jsonb,
    unique (id, owner_id),
    unique (owner_id, file_hash),
    check (
        (source_storage_bucket is null and source_storage_path is null)
        or (source_storage_bucket is not null and source_storage_path is not null)
    )
);

create table public.nodes (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    book_id bigint not null,
    parent_id bigint,
    toc_index integer not null check (toc_index >= 0),
    toc_level integer not null check (toc_level > 0),
    node_type text not null,
    title text not null,
    path_text text not null,
    path_json jsonb not null,
    start_page integer not null check (start_page > 0),
    end_page integer not null check (end_page >= start_page),
    direct_text text not null default '',
    direct_char_count integer generated always as (length(direct_text)) stored,
    unique (id, book_id, owner_id),
    unique (book_id, toc_index),
    foreign key (book_id, owner_id)
        references public.books(id, owner_id) on delete cascade,
    foreign key (parent_id, book_id, owner_id)
        references public.nodes(id, book_id, owner_id) on delete cascade
);

create table public.content_blocks (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    book_id bigint not null,
    node_id bigint not null,
    block_index integer not null check (block_index >= 0),
    block_type text not null check (block_type in ('text', 'table', 'image')),
    category text not null,
    page_number integer not null check (page_number > 0),
    text_content text,
    metadata_json jsonb not null default '{}'::jsonb,
    unique (id, book_id, owner_id),
    unique (node_id, block_index),
    foreign key (node_id, book_id, owner_id)
        references public.nodes(id, book_id, owner_id) on delete cascade
);

create table public.table_blocks (
    block_id bigint primary key,
    owner_id uuid not null,
    book_id bigint not null,
    html_content text,
    flat_text text not null,
    unique (block_id, book_id, owner_id),
    foreign key (block_id, book_id, owner_id)
        references public.content_blocks(id, book_id, owner_id) on delete cascade
);

create table public.image_blocks (
    block_id bigint primary key,
    owner_id uuid not null,
    book_id bigint not null,
    mime_type text not null,
    base64_content text not null,
    unique (block_id, book_id, owner_id),
    foreign key (block_id, book_id, owner_id)
        references public.content_blocks(id, book_id, owner_id) on delete cascade
);

create table public.chunk_builds (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    source_book_id bigint not null,
    source_file_hash text not null check (source_file_hash ~ '^[0-9a-f]{64}$'),
    parser_version text not null,
    chunker_version text not null,
    config_json jsonb not null,
    config_hash text not null check (config_hash ~ '^[0-9a-f]{64}$'),
    built_at timestamptz not null,
    chunk_count integer not null check (chunk_count >= 0),
    unique (id, source_book_id, owner_id),
    unique (
        owner_id, source_book_id, parser_version, chunker_version, config_hash
    ),
    foreign key (source_book_id, owner_id)
        references public.books(id, owner_id) on delete cascade
);

create table public.chunks (
    id text primary key check (id ~ '^[0-9a-f]{64}$'),
    owner_id uuid not null,
    build_id bigint not null,
    source_book_id bigint not null,
    source_node_id bigint not null,
    toc_index integer not null check (toc_index >= 0),
    chunk_index integer not null check (chunk_index >= 0),
    section_title text not null,
    path_text text not null,
    start_page integer not null check (start_page > 0),
    end_page integer not null check (end_page >= start_page),
    text text not null check (length(text) > 0),
    content_types text[] not null,
    char_count integer generated always as (length(text)) stored,
    token_count integer not null check (token_count > 0),
    content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
    search_vector tsvector generated always as (
        setweight(to_tsvector('english', coalesce(section_title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(path_text, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(text, '')), 'D')
    ) stored,
    unique (id, source_book_id, owner_id),
    unique (build_id, toc_index, chunk_index),
    foreign key (build_id, source_book_id, owner_id)
        references public.chunk_builds(id, source_book_id, owner_id)
        on delete cascade,
    foreign key (source_node_id, source_book_id, owner_id)
        references public.nodes(id, book_id, owner_id) on delete cascade
);

create table public.chunk_sources (
    chunk_id text not null,
    owner_id uuid not null,
    source_book_id bigint not null,
    source_order integer not null check (source_order >= 0),
    source_block_id bigint not null,
    block_index integer not null check (block_index >= 0),
    page_number integer not null check (page_number > 0),
    block_type text not null check (block_type in ('text', 'table', 'image')),
    category text not null,
    start_offset integer not null check (start_offset >= 0),
    end_offset integer not null check (end_offset >= start_offset),
    primary key (chunk_id, source_order),
    foreign key (chunk_id, source_book_id, owner_id)
        references public.chunks(id, source_book_id, owner_id) on delete cascade,
    foreign key (source_block_id, source_book_id, owner_id)
        references public.content_blocks(id, book_id, owner_id) on delete cascade
);

create table public.chunk_embeddings (
    chunk_id text primary key,
    owner_id uuid not null,
    source_book_id bigint not null,
    embedding extensions.vector(3072) not null,
    model_name text not null,
    model_revision text not null,
    dimension integer not null check (dimension = 3072),
    document_format_version text not null,
    embedding_input_hash text not null
        check (embedding_input_hash ~ '^[0-9a-f]{64}$'),
    created_at timestamptz not null,
    foreign key (chunk_id, source_book_id, owner_id)
        references public.chunks(id, source_book_id, owner_id) on delete cascade
);

create index idx_nodes_owner_book_parent
    on public.nodes (owner_id, book_id, parent_id);
create index idx_nodes_owner_book_pages
    on public.nodes (owner_id, book_id, start_page, end_page);
create index idx_content_blocks_owner_node
    on public.content_blocks (owner_id, node_id, block_index);
create index idx_chunk_builds_owner_book
    on public.chunk_builds (owner_id, source_book_id);
create index idx_chunks_owner_book_node
    on public.chunks (owner_id, source_book_id, source_node_id);
create index idx_chunks_build_order
    on public.chunks (build_id, toc_index, chunk_index);
create index idx_chunks_search_vector
    on public.chunks using gin (search_vector);
create index idx_chunk_sources_owner_block
    on public.chunk_sources (owner_id, source_block_id);
create index idx_chunk_embeddings_owner_book
    on public.chunk_embeddings (owner_id, source_book_id);

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'books', 'nodes', 'content_blocks', 'table_blocks', 'image_blocks',
        'chunk_builds', 'chunks', 'chunk_sources', 'chunk_embeddings'
    ] loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format(
            'create policy %I on public.%I for all to authenticated '
            'using (owner_id = (select auth.uid())) '
            'with check (owner_id = (select auth.uid()))',
            table_name || '_owner_access',
            table_name
        );
        execute format(
            'grant select, insert, update, delete on public.%I to authenticated',
            table_name
        );
    end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;
