-- Video conversations are isolated from book conversations while preserving
-- the same server-authoritative follow-up and query-rewrite mechanics. Every
-- turn pins the published ingestion version that supplied its evidence.

create table video.conversations (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    video_id uuid not null,
    title text not null default 'New conversation' check (btrim(title) <> ''),
    retrieval_mode text not null default 'hybrid_rerank' check (
        retrieval_mode in ('bm25', 'vector', 'hybrid', 'hybrid_rerank')
    ),
    retrieval_config_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(retrieval_config_json) = 'object'
    ),
    prompt_snapshot_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(prompt_snapshot_json) = 'object'
    ),
    state_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(state_json) = 'object'
    ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, video_id, owner_id),
    foreign key (video_id, owner_id)
        references video.videos(id, owner_id) on delete cascade
);

create index idx_video_conversations_owner_updated
    on video.conversations (owner_id, updated_at desc, id);
create index idx_video_conversations_owner_video
    on video.conversations (owner_id, video_id, updated_at desc);

create table video.conversation_turns (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    conversation_id uuid not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    turn_index integer not null check (turn_index >= 0),
    status text not null default 'running' check (
        status in ('running', 'complete', 'failed')
    ),
    question text not null check (btrim(question) <> ''),
    rewritten_query text,
    answer text,
    result_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(result_json) = 'object'
    ),
    actual_cost_usd numeric(10, 6) not null default 0 check (
        actual_cost_usd >= 0 and actual_cost_usd <= 0.05
    ),
    trace_id text,
    error_code text,
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (id, conversation_id, owner_id),
    unique (conversation_id, turn_index),
    foreign key (conversation_id, video_id, owner_id)
        references video.conversations(id, video_id, owner_id)
        on delete cascade,
    foreign key (ingestion_version_id, video_id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        deferrable initially deferred,
    check (
        (status = 'running'
            and completed_at is null
            and answer is null
            and error_code is null)
        or
        (status = 'complete'
            and completed_at is not null
            and rewritten_query is not null
            and btrim(rewritten_query) <> ''
            and answer is not null
            and btrim(answer) <> ''
            and result_json <> '{}'::jsonb
            and error_code is null
            and error_message is null)
        or
        (status = 'failed'
            and completed_at is not null
            and answer is null
            and error_code is not null
            and btrim(error_code) <> '')
    ),
    check (completed_at is null or completed_at >= created_at)
);

create index idx_video_conversation_turns_owner_conversation
    on video.conversation_turns (owner_id, conversation_id, turn_index);
create index idx_video_conversation_turns_owner_trace
    on video.conversation_turns (owner_id, trace_id)
    where trace_id is not null;

create or replace function video.validate_turn_ingestion_version()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
    version_status text;
begin
    select version.status
    into version_status
    from video.ingestion_versions as version
    where version.id = new.ingestion_version_id
      and version.video_id = new.video_id
      and version.owner_id = new.owner_id;

    if version_status is null
       or version_status not in ('ready', 'degraded') then
        raise check_violation using message =
            'video turns require a published ready or degraded ingestion version';
    end if;
    return new;
end;
$$;

create trigger conversation_turns_validate_version
    before insert or update of ingestion_version_id, video_id, owner_id
    on video.conversation_turns
    for each row execute function video.validate_turn_ingestion_version();

create trigger video_conversations_set_updated_at
    before update on video.conversations
    for each row execute function video.set_updated_at();
create trigger video_conversation_turns_set_updated_at
    before update on video.conversation_turns
    for each row execute function video.set_updated_at();

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'conversations', 'conversation_turns'
    ] loop
        execute format('alter table video.%I enable row level security', table_name);
        execute format(
            'create policy %I on video.%I for select to authenticated '
            'using (owner_id = (select auth.uid()))',
            table_name || '_owner_read',
            table_name
        );
        execute format(
            'grant select on video.%I to authenticated',
            table_name
        );
    end loop;
end $$;

comment on column video.conversation_turns.result_json is
    'Grounded answer and immutable citation/evidence snapshot; prior answers are never evidence.';
