-- Productize the course aggregation layer and preserve multi-lecture turn
-- provenance. Lecture evidence remains canonical in the existing video tables.

alter table video.courses
    add column creation_key uuid;

create unique index idx_video_courses_owner_creation_key
    on video.courses (owner_id, creation_key)
    where creation_key is not null;

create table video.course_conversations (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null,
    course_id uuid not null,
    title text not null default 'New conversation' check (btrim(title) <> ''),
    selected_video_ids uuid[] not null check (
        cardinality(selected_video_ids) between 1 and 100
    ),
    prompt_snapshot_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(prompt_snapshot_json) = 'object'
    ),
    state_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(state_json) = 'object'
    ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, course_id, owner_id),
    unique (id, owner_id),
    foreign key (course_id, owner_id)
        references video.courses(id, owner_id) on delete cascade
);

create index idx_video_course_conversations_owner_course
    on video.course_conversations (owner_id, course_id, updated_at desc, id);

create table video.course_conversation_turns (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    conversation_id uuid not null,
    course_id uuid not null,
    turn_index integer not null check (turn_index >= 0),
    status text not null default 'running' check (
        status in ('running', 'complete', 'failed')
    ),
    question text not null check (btrim(question) <> ''),
    rewritten_query text,
    answer text,
    result_json jsonb not null default '{}'::jsonb check (
        jsonb_typeof(result_json) = 'object'
    ),
    actual_cost_usd numeric(10, 6) not null default 0 check (
        actual_cost_usd >= 0 and actual_cost_usd <= 0.05
    ),
    trace_id text,
    error_code text,
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (id, conversation_id, owner_id),
    unique (conversation_id, turn_index),
    foreign key (conversation_id, course_id, owner_id)
        references video.course_conversations(id, course_id, owner_id)
        on delete cascade,
    check (
        (status = 'running' and completed_at is null and answer is null
            and error_code is null)
        or
        (status = 'complete' and completed_at is not null
            and rewritten_query is not null and btrim(rewritten_query) <> ''
            and answer is not null and btrim(answer) <> ''
            and result_json <> '{}'::jsonb
            and error_code is null and error_message is null)
        or
        (status = 'failed' and completed_at is not null and answer is null
            and error_code is not null and btrim(error_code) <> '')
    ),
    check (completed_at is null or completed_at >= created_at)
);

create index idx_video_course_turns_owner_conversation
    on video.course_conversation_turns (owner_id, conversation_id, turn_index);

create table video.course_turn_versions (
    owner_id uuid not null,
    conversation_id uuid not null,
    turn_id bigint not null,
    video_id uuid not null,
    ingestion_version_id uuid not null,
    primary key (turn_id, video_id),
    foreign key (turn_id, conversation_id, owner_id)
        references video.course_conversation_turns(id, conversation_id, owner_id)
        on delete cascade,
    foreign key (ingestion_version_id, video_id, owner_id)
        references video.ingestion_versions(id, video_id, owner_id)
        deferrable initially deferred
);

create index idx_video_course_turn_versions_owner_turn
    on video.course_turn_versions (owner_id, turn_id, video_id);

create or replace function video.validate_course_turn_version()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
    version_status text;
begin
    select version.status into version_status
    from video.ingestion_versions as version
    where version.id = new.ingestion_version_id
      and version.video_id = new.video_id
      and version.owner_id = new.owner_id;

    if version_status is null or version_status not in ('ready', 'degraded') then
        raise check_violation using message =
            'course turns require published ready or degraded ingestion versions';
    end if;
    return new;
end;
$$;

create trigger course_turn_versions_validate_version
    before insert or update of ingestion_version_id, video_id, owner_id
    on video.course_turn_versions
    for each row execute function video.validate_course_turn_version();

create trigger course_conversations_set_updated_at
    before update on video.course_conversations
    for each row execute function video.set_updated_at();

create trigger course_conversation_turns_set_updated_at
    before update on video.course_conversation_turns
    for each row execute function video.set_updated_at();

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'course_conversations', 'course_conversation_turns',
        'course_turn_versions'
    ] loop
        execute format('alter table video.%I enable row level security', table_name);
        execute format(
            'create policy %I on video.%I for select to authenticated '
            'using (owner_id = (select auth.uid()))',
            table_name || '_owner_read', table_name
        );
        execute format('grant select on video.%I to authenticated', table_name);
    end loop;
end $$;

comment on table video.course_turn_versions is
    'Published lecture versions used by one immutable multi-lecture course turn.';
